# Generated by Django 2.2.7 on 2019-12-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetracker',
            old_name='Remarks',
            new_name='Remark',
        ),
    ]
