# Generated by Django 2.2.7 on 2019-12-07 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20191204_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymentnumber',
        ),
        migrations.AddField(
            model_name='payment',
            name='statementperiod',
            field=models.DateField(default=datetime.date(2019, 12, 7)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Paynote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2019, 12, 7)),
        ),
    ]
