# Generated by Django 2.2.7 on 2019-12-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_auto_20191209_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statementperiod',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
    ]
